# Generated by Django 4.2.6 on 2023-10-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0003_alter_category_id_alter_customer_id_alter_items_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcard',
            name='total_price',
            field=models.CharField(max_length=10),
        ),
    ]
