# Generated by Django 4.2.6 on 2023-10-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_remove_shopcard_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcard',
            name='total_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
