# Generated by Django 4.2.6 on 2023-10-25 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0006_shopcard_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='product',
        ),
        migrations.RemoveField(
            model_name='items',
            name='shopcard_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='shopcard',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shopcard',
        ),
    ]
