# Generated by Django 4.2.6 on 2023-10-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0011_remove_category_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
